### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by hwaterke** [waiting-for-dev/warden-jwt_auth#1]
Hey,

Would it be possible to have a simple app demonstrating how to use the gem?
I'm not sure about how to create the token in the first place (during login)

Am I supposed to use another Warden strategy based on Username/password and call `Warden::JWTAuth::UserEncoder.new.call(user, :user)` after retrieving my User and send that back to the frontend?

Thanks in advance for your help.

**Comment by waiting-for-dev** [comment]
Hi @hwaterke ,

> Would it be possible to have a simple app demonstrating how to use the gem?

If you want to see an example rack application using this gem you can take a look at the [integration tests](https://github.com/waiting-for-dev/warden-jwt_auth/tree/master/spec/warden/jwt_auth/features).

> I'm not sure about how to create the token in the first place (during login)

> Am I supposed to use another Warden strategy based on Username/password and call Warden::JWTAuth::UserEncoder.new.call(user, :user) after retrieving my User and send that back to the frontend?

The information in the [Token dispatch configuration in the README](https://github.com/waiting-for-dev/warden-jwt_auth#token-dispatch-configuration) can help you:

> You need to tell which requests will dispatch tokens for the user that has been previously authenticated (usually through some other warden strategy, such as one requiring username and email parameters).

> To configure it, you must provide a bidimensional array, each item being an array of two elements: the request method and a regular expression that must match the request path.

> For example:

> config.dispatch_requests = [
                                                 ['POST', %r{^/sign_in$}]
                                               ]

So, yes, you need to authenticate the user in some other way in order to get a valid token from the server. But you don't have to call `UserEncoder#call` youself, just configure your `sign_in` request in `config.dispatch_requests`.

Just in case, if you are using Rails & devise you are better off using [devise-jwt](https://github.com/waiting-for-dev/devise-jwt), which is a small layer on top of this gem.

Hope it helps.

**Comment by hwaterke** [comment]
Hey, thanks a lot for your explanations @waiting-for-dev 

I've played a bit with it and here's a demo app in case Google sends someone here.

Based on Sinatra:
```ruby
require 'sinatra'
require 'warden'
require 'warden/jwt_auth'
require 'singleton'

# An user record
class User
  include Singleton
  def jwt_subject
    1
  end
end

# User repository
class UserRepo
  def self.find_for_jwt_authentication(_sub)
    User.instance
  end
end

class RevocationStrategy
  def self.jwt_revoked?(payload, user)
    false
  end
end

Warden::JWTAuth.configure do |config|
  config.secret = 'super-secret'
  config.mappings = { default: UserRepo }
  config.dispatch_requests = [['POST', %r{^/login$}]]
  config.revocation_strategies = { default: RevocationStrategy }
end

use Warden::JWTAuth::Middleware

use Warden::Manager do |manager|
  manager.default_strategies(:jwt)
  manager.failure_app = ->(_env) { [401, {}, ['unauthorized']] }
end

get '/protected' do
  env['warden'].authenticate!
  'Sensitive data'
end

post '/login' do
  # TODO Check username / password
  env['warden'].set_user(User.instance, :store => false)
  'Logged in'
end
```

**Comment by waiting-for-dev** [comment]
Happy to help. Thanks for your example code. With your permission, I will copy it to the Wiki of the project so it can be easily found for others.

I'll close this issue. Feel free to reopen if you have more doubts.

**Comment by hwaterke** [comment]
Sure, feel free to use it however you want! That's why I posted it 🙂
Took me a bit of fiddling in the tests to get how it works so if that can help others that's great!

**Comment by waiting-for-dev** [comment]
Ok, added ;)
